### ISSUE TITLE
discussion: 빌더 패턴과 스태틱 메서드 사용 기준 정하기

### ISSUE THREAD

**Issue by BomLee427** [MyohanMeeting/MeMyo-Backend#26]
지금은 너무 대중없이 사용하는 것 같아서...이야기해보면 좋겠습니당
저는 개인적으로 클래스 변수의 수가 5개 이상이거나, 같은 타입의 클래스 변수가 2~3개 이상 중복될 경우엔 빌더패턴을 쓰면 좋을 것 같아요.
빌더패턴을 일괄로 적용하는 것도 나쁘진 않을 거 같은데 품이 좀 들 거 같아서...편하게 의견주세용!

**Comment by Jungbae99** [comment]
5개 이상이면 빌더패턴 확인했습니다!

**Comment by DevelopJJong** [comment]
넹 알겠습니댜

**Comment by BomLee427** [comment]
웹훅 알림 테스트
